# Generated by Django 6.0 on 2025-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_owner', models.CharField(max_length=255)),
                ('repo_url', models.URLField(unique=True)),
                ('score_overall', models.PositiveSmallIntegerField()),
                ('rank', models.CharField(max_length=50)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score_overall', 'repo_name'],
                'unique_together': {('repo_owner', 'repo_name')},
            },
        ),
    ]
